-- LIFE OS v3.2 long-term adaptation layers

ALTER TABLE "WeightConfig"
  ADD COLUMN IF NOT EXISTS "debtCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.96,
  ADD COLUMN IF NOT EXISTS "debtRecoveryFactor" DOUBLE PRECISION NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS "adaptiveCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.98;

ALTER TABLE "BioStateSnapshot"
  ADD COLUMN IF NOT EXISTS "recoveryDebt" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "adaptiveCapacity" DOUBLE PRECISION NOT NULL DEFAULT 50;
