-- Add v3 bio-simulator state persistence and bio config defaults

-- WeightConfig bio parameters
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "momentumWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.15;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "reserveSleepGain" DOUBLE PRECISION NOT NULL DEFAULT 0.06;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "reserveWorkCost" DOUBLE PRECISION NOT NULL DEFAULT 0.03;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "reserveStressCost" DOUBLE PRECISION NOT NULL DEFAULT 0.04;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "fatigueCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.92;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "fatigueWorkGain" DOUBLE PRECISION NOT NULL DEFAULT 0.025;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "fatigueStressGain" DOUBLE PRECISION NOT NULL DEFAULT 0.03;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "fatigueSleepRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0.045;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "strainCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.90;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "strainFatigueWeight" DOUBLE PRECISION NOT NULL DEFAULT 0.45;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "overloadLevel1Threshold" DOUBLE PRECISION NOT NULL DEFAULT 45;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "overloadLevel2Threshold" DOUBLE PRECISION NOT NULL DEFAULT 70;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "overloadRecoverThreshold" DOUBLE PRECISION NOT NULL DEFAULT 35;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "baseFocus" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "focusFromEnergy" DOUBLE PRECISION NOT NULL DEFAULT 0.11;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "focusFromFatigue" DOUBLE PRECISION NOT NULL DEFAULT 0.09;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "focusFromStress" DOUBLE PRECISION NOT NULL DEFAULT 0.12;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "optLoadMin" DOUBLE PRECISION NOT NULL DEFAULT 0.35;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "optLoadMax" DOUBLE PRECISION NOT NULL DEFAULT 0.75;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "adaptGain" DOUBLE PRECISION NOT NULL DEFAULT 0.03;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "burnoutPenalty" DOUBLE PRECISION NOT NULL DEFAULT 0.06;
ALTER TABLE "WeightConfig" ADD COLUMN IF NOT EXISTS "disciplineCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.96;

-- BioStateSnapshot model
CREATE TABLE IF NOT EXISTS "BioStateSnapshot" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "date" DATE NOT NULL,
  "energyReserve" DOUBLE PRECISION NOT NULL,
  "cognitiveFatigue" DOUBLE PRECISION NOT NULL,
  "strainIndex" DOUBLE PRECISION NOT NULL,
  "overloadLevel" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BioStateSnapshot_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "BioStateSnapshot_userId_date_key" ON "BioStateSnapshot"("userId", "date");
CREATE INDEX IF NOT EXISTS "BioStateSnapshot_userId_date_idx" ON "BioStateSnapshot"("userId", "date");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'BioStateSnapshot_userId_fkey'
  ) THEN
    ALTER TABLE "BioStateSnapshot"
      ADD CONSTRAINT "BioStateSnapshot_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "User"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
