import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { ApiError, errorResponse } from "@/lib/api/errors";
import { devSimulationExportPayloadSchema } from "@/lib/api/schemas";
import { ensureUserWithPlan } from "@/lib/api/plan";
import { formatDateOnly, toUtcDateOnly } from "@/lib/api/date";
import { isAdmin } from "@/lib/authz";
import { getCalibrationStage } from "@/lib/calibrationStage";
import { deriveSystemStatus } from "@/lib/control-room/systemStatus";
import { computeIntegrity, type IntegrityConstraint } from "@/lib/engine/systemIntegrity";
import { evaluateGuardrailWithContext } from "@/lib/guardrails/guardrailEngine";
import { prisma } from "@/lib/prisma";
import {
  SIMULATION_NOTE_MARKER_BURNOUT,
  SIMULATION_NOTE_MARKER_RANDOM,
  SIMULATION_NOTE_MARKER_RECOVERY,
} from "@/lib/dev/simulateCheckins";

const SIMULATION_NOTE_MARKERS = [
  SIMULATION_NOTE_MARKER_RANDOM,
  SIMULATION_NOTE_MARKER_BURNOUT,
  SIMULATION_NOTE_MARKER_RECOVERY,
];

type ParsedCheckinPayload = {
  sleepHours?: number;
  sleepQuality?: number;
  bedtimeMinutes?: number;
  wakeTimeMinutes?: number;
  workout?: number;
  deepWorkMin?: number;
  learningMin?: number;
  moneyDelta?: number;
  stress?: number;
  noteText?: string | null;
};

type SystemMetricsSnapshot = {
  load: number;
  recovery: number;
  risk: number;
  burnout: number;
};

function devToolsEnabled(): boolean {
  return process.env.NODE_ENV === "development" || process.env.NEXT_PUBLIC_DEV_TOOLS === "true";
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

function round1(value: number): number {
  return Math.round(value * 10) / 10;
}

function average(values: number[]): number {
  if (values.length === 0) return 0;
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function countTrailingTrue(values: boolean[]): number {
  let count = 0;
  for (let index = values.length - 1; index >= 0; index -= 1) {
    if (!values[index]) break;
    count += 1;
  }
  return count;
}

function asNumber(value: { toString(): string } | number | null | undefined): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (!value) return null;
  const parsed = Number(value.toString());
  return Number.isFinite(parsed) ? parsed : null;
}

function asObject(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== "object") return null;
  return value as Record<string, unknown>;
}

function toStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === "string");
}

function parseProtocolTriggerContext(inputs: unknown): {
  source: string | null;
  autoGenerated: boolean | null;
  triggerReasons: string[];
  guardrailPressureReasons: string[];
} {
  const payload = asObject(inputs);
  if (!payload) {
    return {
      source: null,
      autoGenerated: null,
      triggerReasons: [],
      guardrailPressureReasons: [],
    };
  }

  return {
    source: typeof payload.source === "string" ? payload.source : null,
    autoGenerated: typeof payload.autoGenerated === "boolean" ? payload.autoGenerated : null,
    triggerReasons: toStringArray(payload.triggerReasons),
    guardrailPressureReasons: toStringArray(payload.guardrailPressureReasons),
  };
}

function deriveRecoveryPatternForGuardrail(input: {
  lifeScoreDelta7d: number | null;
  riskDelta7d: number | null;
  burnoutDelta7d: number | null;
  load: number;
  recovery: number;
  sleepHours: number | null | undefined;
  sleepQuality: number | null | undefined;
  stress: number | null | undefined;
  deepWorkMin: number | null | undefined;
  workout: number | null | undefined;
  circadianAlignment: number;
}): { streakDays: number; strength: number } | null {
  const lifeScoreDelta7d = input.lifeScoreDelta7d ?? 0;
  const riskDelta7d = input.riskDelta7d ?? 0;
  const burnoutDelta7d = input.burnoutDelta7d ?? 0;
  let score = 0;

  if (riskDelta7d <= -3) score += 1.6;
  if (burnoutDelta7d <= -2) score += 1.2;
  if (lifeScoreDelta7d >= 1.5) score += 1;
  if (input.recovery >= input.load + 2) score += 1.2;
  if ((input.sleepHours ?? 0) >= 6.9) score += 0.8;
  if ((input.sleepQuality ?? 0) >= 3.4) score += 0.7;
  if ((input.stress ?? 10) <= 6.1) score += 0.8;
  if ((input.deepWorkMin ?? 180) <= 120) score += 0.7;
  if ((input.workout ?? 0) > 0) score += 0.4;
  if (input.circadianAlignment >= 66) score += 0.6;

  if (score < 4) return null;

  const streakDays = clamp(
    Math.round(
      1 +
        (riskDelta7d <= -8 ? 4 : riskDelta7d <= -4 ? 3 : riskDelta7d <= -2 ? 2 : 1) +
        (burnoutDelta7d <= -6 ? 3 : burnoutDelta7d <= -3 ? 2 : burnoutDelta7d <= -1 ? 1 : 0)
    ),
    1,
    10
  );
  const strength = clamp(score / 8.5, 0, 1);
  if (streakDays < 3 || strength < 0.5) return null;

  return { streakDays, strength };
}

function isAutoClearedProtocolRun(run: { appliedAt: Date | null; outcome: unknown }): boolean {
  if (run.appliedAt) return false;
  const outcome = asObject(run.outcome);
  return outcome?.autoCleared === true;
}

function getAutoClearReason(outcome: unknown): string | null {
  const payload = asObject(outcome);
  if (!payload) return null;
  return typeof payload.reason === "string" ? payload.reason : null;
}

function parseCheckinPayload(notes: string | null): ParsedCheckinPayload {
  if (!notes) return {};
  try {
    const parsed = JSON.parse(notes) as Record<string, unknown>;
    return {
      sleepHours: typeof parsed.sleepHours === "number" ? parsed.sleepHours : undefined,
      sleepQuality: typeof parsed.sleepQuality === "number" ? parsed.sleepQuality : undefined,
      bedtimeMinutes: typeof parsed.bedtimeMinutes === "number" ? parsed.bedtimeMinutes : undefined,
      wakeTimeMinutes: typeof parsed.wakeTimeMinutes === "number" ? parsed.wakeTimeMinutes : undefined,
      workout: typeof parsed.workout === "number" ? parsed.workout : undefined,
      deepWorkMin: typeof parsed.deepWorkMin === "number" ? parsed.deepWorkMin : undefined,
      learningMin: typeof parsed.learningMin === "number" ? parsed.learningMin : undefined,
      moneyDelta: typeof parsed.moneyDelta === "number" ? parsed.moneyDelta : undefined,
      stress:
        typeof parsed.stress === "number"
          ? parsed.stress
          : typeof parsed.stressLevel === "number"
            ? parsed.stressLevel
            : undefined,
      noteText: typeof parsed.noteText === "string" ? parsed.noteText : null,
    };
  } catch {
    return {};
  }
}

function countConstraints(protocol: unknown): number {
  if (!protocol || typeof protocol !== "object") return 0;
  const maybe = protocol as { constraints?: unknown };
  return Array.isArray(maybe.constraints) ? maybe.constraints.length : 0;
}

function parseProtocolConstraints(value: unknown): IntegrityConstraint[] {
  if (!value || typeof value !== "object") return [];
  const protocol = value as Record<string, unknown>;
  if (!Array.isArray(protocol.constraints)) return [];

  return protocol.constraints
    .map((item) => {
      if (!item || typeof item !== "object") return null;
      const row = item as Record<string, unknown>;
      if (typeof row.label !== "string" || typeof row.value !== "string") return null;
      const severity = row.severity === "hard" ? "hard" : row.severity === "soft" ? "soft" : null;
      if (!severity) return null;
      return { label: row.label, value: row.value, severity };
    })
    .filter((item): item is IntegrityConstraint => item !== null);
}

function getDateRangeDays(startDate: Date, endDate: Date): number {
  const diffMs = endDate.getTime() - startDate.getTime();
  return Math.floor(diffMs / 86400000) + 1;
}

function buildDayKeys(startDate: Date, days: number): string[] {
  const keys: string[] = [];
  for (let index = 0; index < days; index += 1) {
    const date = new Date(startDate);
    date.setUTCDate(startDate.getUTCDate() + index);
    keys.push(formatDateOnly(date));
  }
  return keys;
}

function toTimestampFilePart(date: Date): string {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");
  const day = String(date.getUTCDate()).padStart(2, "0");
  const hours = String(date.getUTCHours()).padStart(2, "0");
  const minutes = String(date.getUTCMinutes()).padStart(2, "0");
  const seconds = String(date.getUTCSeconds()).padStart(2, "0");
  return `${year}-${month}-${day}-${hours}${minutes}${seconds}`;
}

function computeMetricsFromBio(input: {
  energyReserve: number;
  cognitiveFatigue: number;
  strainIndex: number;
  stressLoad: number;
  burnoutRiskIndex: number;
  parasympatheticDrive: number;
  resilienceIndex: number;
}): SystemMetricsSnapshot {
  const load = clamp(input.cognitiveFatigue * 0.45 + input.strainIndex * 0.35 + input.stressLoad * 0.2, 0, 100);
  const recovery = clamp(
    input.energyReserve * 0.45 + input.parasympatheticDrive * 0.25 + input.resilienceIndex * 0.3,
    0,
    100
  );
  const risk = clamp(input.burnoutRiskIndex * 0.5 + input.strainIndex * 0.35 + (100 - input.energyReserve) * 0.15, 0, 100);
  return {
    load: round1(load),
    recovery: round1(recovery),
    risk: round1(risk),
    burnout: round1(clamp(input.burnoutRiskIndex, 0, 100)),
  };
}

function factorLabel(factorType: string): string {
  switch (factorType) {
    case "SLEEP":
      return "Sleep";
    case "WORKOUT":
      return "Workout";
    case "DEEP_WORK":
      return "Deep Work";
    case "LEARNING":
      return "Learning";
    case "MONEY_DELTA":
      return "Money Delta";
    case "STRESS":
      return "Stress";
    case "OVERLOAD":
      return "Overload";
    case "MOMENTUM":
      return "Momentum";
    default:
      return factorType;
  }
}

function stabilityStateFromGuardrail(guardrail: "OPEN" | "CAUTION" | "LOCKDOWN"): "Stable" | "Sensitive" | "Strained" {
  if (guardrail === "LOCKDOWN") return "Strained";
  if (guardrail === "CAUTION") return "Sensitive";
  return "Stable";
}

export async function POST(request: Request) {
  try {
    if (!devToolsEnabled()) throw new ApiError(404, "Not found");
    const session = await auth();
    const sessionUserId = session?.user?.id;
    if (!sessionUserId) throw new ApiError(401, "Unauthorized");

    const payload = devSimulationExportPayloadSchema.parse(await request.json());
    const startDate = toUtcDateOnly(payload.startDateISO);
    const endDate = toUtcDateOnly(payload.endDateISO);
    if (startDate.getTime() > endDate.getTime()) {
      throw new ApiError(400, "startDateISO must be <= endDateISO.");
    }

    const rangeDays = getDateRangeDays(startDate, endDate);
    if (rangeDays > 90) {
      throw new ApiError(400, "Export range is too large. Max 90 days.");
    }

    const sessionUser = await prisma.user.findUnique({
      where: { id: sessionUserId },
      select: { id: true, email: true, role: true },
    });
    const admin = isAdmin(sessionUser);
    if (!admin && payload.userId !== sessionUserId) {
      throw new ApiError(403, "Debug export is allowed only for the current user.");
    }

    const user = await ensureUserWithPlan(payload.userId, request);
    const targetUserState = await prisma.user.findUnique({
      where: { id: user.id },
      select: {
        calibrationCheckinsNeeded: true,
        adaptiveRiskOffset: true,
      },
    });
    if (!targetUserState) {
      throw new ApiError(404, "User not found.");
    }

    const dayKeys = buildDayKeys(startDate, rangeDays);

    const [checkins, statSnapshots, bioSnapshots, contributions, antiChaosPlans, protocolRuns, allCheckinDates] = await Promise.all([
      prisma.dailyCheckIn.findMany({
        where: {
          userId: user.id,
          date: { gte: startDate, lte: endDate },
        },
        orderBy: { date: "asc" },
        select: {
          id: true,
          date: true,
          createdAt: true,
          updatedAt: true,
          mood: true,
          stressLevel: true,
          energyLevel: true,
          systemStatus: true,
          bedtimeMinutes: true,
          wakeTimeMinutes: true,
          notes: true,
          configVersion: true,
        },
      }),
      prisma.statSnapshot.findMany({
        where: {
          userId: user.id,
          date: { gte: startDate, lte: endDate },
        },
        orderBy: { date: "asc" },
        select: {
          id: true,
          date: true,
          lifeScore: true,
          health: true,
          relationships: true,
          career: true,
          finance: true,
          personalGrowth: true,
          systemStatus: true,
          configVersion: true,
        },
      }),
      prisma.bioStateSnapshot.findMany({
        where: {
          userId: user.id,
          date: { gte: startDate, lte: endDate },
        },
        orderBy: { date: "asc" },
        select: {
          date: true,
          energyReserve: true,
          cognitiveFatigue: true,
          strainIndex: true,
          overloadLevel: true,
          recoveryDebt: true,
          adaptiveCapacity: true,
          sleepBuffer: true,
          circadianAlignment: true,
          sleepRegularity: true,
          stressLoad: true,
          trainingBuffer: true,
          homeostasisBias: true,
          cognitiveSaturation: true,
          sympatheticDrive: true,
          parasympatheticDrive: true,
          autonomicBalance: true,
          hormeticSignal: true,
          overstressSignal: true,
          burnoutRiskIndex: true,
          resilienceIndex: true,
        },
      }),
      prisma.statContribution.findMany({
        where: {
          userId: user.id,
          date: { gte: startDate, lte: endDate },
        },
        orderBy: [{ date: "asc" }, { statType: "asc" }, { factorType: "asc" }],
        select: {
          id: true,
          date: true,
          statType: true,
          factorType: true,
          contribution: true,
        },
      }),
      prisma.antiChaosPlan.findMany({
        where: {
          userId: user.id,
          date: { lte: endDate },
        },
        orderBy: { date: "asc" },
        select: {
          id: true,
          date: true,
          systemStatus: true,
          reasons: true,
          actionItems: true,
          isResolved: true,
          resolvedDate: true,
          createdAt: true,
        },
      }),
      prisma.protocolRun.findMany({
        where: {
          userId: user.id,
          OR: [{ createdAt: { lte: endDate } }, { appliedAt: { lte: endDate } }],
        },
        orderBy: [{ appliedAt: "desc" }, { createdAt: "desc" }],
        take: 500,
        select: {
          id: true,
          createdAt: true,
          appliedAt: true,
          horizonHours: true,
          mode: true,
          guardrailState: true,
          confidence: true,
          inputs: true,
          protocol: true,
          outcome: true,
        },
      }),
      prisma.dailyCheckIn.findMany({
        where: {
          userId: user.id,
          date: { lte: endDate },
        },
        orderBy: { date: "asc" },
        select: { date: true },
      }),
    ]);

    if (checkins.length === 0) {
      throw new ApiError(404, "No check-ins found in selected simulation window.");
    }

    const checkinsByDay = new Map(checkins.map((row) => [formatDateOnly(row.date), row] as const));
    const statsByDay = new Map(statSnapshots.map((row) => [formatDateOnly(row.date), row] as const));
    const bioByDay = new Map(bioSnapshots.map((row) => [formatDateOnly(row.date), row] as const));
    const antiChaosByDay = new Map(antiChaosPlans.map((row) => [formatDateOnly(row.date), row] as const));
    const antiChaosPlansDesc = [...antiChaosPlans].sort((a, b) => b.date.getTime() - a.date.getTime());

    const contributionsByDay = new Map<string, Array<{ statType: string; factorType: string; contribution: number }>>();
    for (const row of contributions) {
      const key = formatDateOnly(row.date);
      const current = contributionsByDay.get(key) ?? [];
      current.push({
        statType: row.statType,
        factorType: row.factorType,
        contribution: asNumber(row.contribution) ?? 0,
      });
      contributionsByDay.set(key, current);
    }

    const checkinDates = allCheckinDates.map((row) => formatDateOnly(row.date));
    let checkinCursor = 0;
    let totalCompletedToDate = 0;
    const totalByDay = new Map<string, number>();
    for (const dayKey of dayKeys) {
      while (checkinCursor < checkinDates.length && checkinDates[checkinCursor] <= dayKey) {
        totalCompletedToDate += 1;
        checkinCursor += 1;
      }
      totalByDay.set(dayKey, totalCompletedToDate);
    }

    const protocolRunsByCreatedDay = new Map<string, typeof protocolRuns>();
    for (const run of protocolRuns) {
      const createdDay = formatDateOnly(run.createdAt);
      if (!protocolRunsByCreatedDay.has(createdDay)) {
        protocolRunsByCreatedDay.set(createdDay, []);
      }
      protocolRunsByCreatedDay.get(createdDay)?.push(run);
    }

    const appliedRuns = protocolRuns
      .filter((run) => run.appliedAt)
      .sort((a, b) => (b.appliedAt ? b.appliedAt.getTime() : 0) - (a.appliedAt ? a.appliedAt.getTime() : 0));

    const metricsByDay = new Map<string, SystemMetricsSnapshot>();
    for (const dayKey of dayKeys) {
      const bio = bioByDay.get(dayKey);
      if (!bio) continue;
      metricsByDay.set(
        dayKey,
        computeMetricsFromBio({
          energyReserve: bio.energyReserve,
          cognitiveFatigue: bio.cognitiveFatigue,
          strainIndex: bio.strainIndex,
          stressLoad: bio.stressLoad,
          burnoutRiskIndex: bio.burnoutRiskIndex,
          parasympatheticDrive: bio.parasympatheticDrive,
          resilienceIndex: bio.resilienceIndex,
        })
      );
    }

    const dayRecords = dayKeys.map((dayKey, index) => {
      const dayDate = new Date(startDate);
      dayDate.setUTCDate(startDate.getUTCDate() + index);
      const dayEnd = new Date(dayDate);
      dayEnd.setUTCHours(23, 59, 59, 999);

      const checkinRow = checkinsByDay.get(dayKey) ?? null;
      const checkinParsed = parseCheckinPayload(checkinRow?.notes ?? null);
      const statRow = statsByDay.get(dayKey) ?? null;
      const bioRow = bioByDay.get(dayKey) ?? null;
      const dayContributions = contributionsByDay.get(dayKey) ?? [];
      const antiChaosHistoryEntry = antiChaosByDay.get(dayKey) ?? null;
      const antiChaosActive = antiChaosPlansDesc.find((plan) => {
        if (plan.date.getTime() > dayEnd.getTime()) return false;
        if (!plan.isResolved) return true;
        return !plan.resolvedDate || plan.resolvedDate.getTime() > dayEnd.getTime();
      });
      const antiChaosResolvedToday =
        antiChaosPlansDesc.find(
          (plan) => plan.resolvedDate && formatDateOnly(plan.resolvedDate) === dayKey
        ) ?? null;
      const antiChaosStatePlan =
        antiChaosActive ?? (antiChaosHistoryEntry?.isResolved ? antiChaosHistoryEntry : antiChaosResolvedToday);
      const antiChaosState =
        antiChaosActive
          ? antiChaosActive.systemStatus === "CRITICAL"
            ? ("critical" as const)
            : ("warning" as const)
          : antiChaosStatePlan
            ? ("resolved_history" as const)
            : ("inactive" as const);

      const generatedProtocolsRaw = protocolRunsByCreatedDay.get(dayKey) ?? [];
      const generatedProtocols = generatedProtocolsRaw.filter((run) => !isAutoClearedProtocolRun(run));
      const clearedProtocols = generatedProtocolsRaw.filter((run) => isAutoClearedProtocolRun(run));
      const metrics = metricsByDay.get(dayKey) ?? null;

      const riskWindow = dayKeys
        .slice(Math.max(0, index - 13), index + 1)
        .map((key) => metricsByDay.get(key))
        .filter((row): row is SystemMetricsSnapshot => row !== undefined);
      const avgRisk14d =
        riskWindow.length > 0
          ? round1(riskWindow.reduce((sum, row) => sum + row.risk, 0) / riskWindow.length)
          : null;
      const recentRiskWindow = riskWindow.slice(-7).map((row) => row.risk);
      const previousRiskWindow = riskWindow.slice(-14, -7).map((row) => row.risk);
      const riskDelta7d =
        recentRiskWindow.length > 0
          ? round1(average(recentRiskWindow) - (previousRiskWindow.length > 0 ? average(previousRiskWindow) : recentRiskWindow[0] ?? 0))
          : null;
      const burnoutWindow = dayKeys
        .slice(Math.max(0, index - 13), index + 1)
        .map((key) => metricsByDay.get(key)?.burnout)
        .filter((value): value is number => typeof value === "number" && Number.isFinite(value));
      const recentBurnoutWindow = burnoutWindow.slice(-7);
      const previousBurnoutWindow = burnoutWindow.slice(-14, -7);
      const burnoutDelta7d =
        recentBurnoutWindow.length > 0
          ? round1(
              average(recentBurnoutWindow) -
                (previousBurnoutWindow.length > 0 ? average(previousBurnoutWindow) : recentBurnoutWindow[0] ?? 0)
            )
          : null;
      const lifeScoreWindow7d = dayKeys
        .slice(Math.max(0, index - 6), index + 1)
        .map((key) => asNumber(statsByDay.get(key)?.lifeScore))
        .filter((value): value is number => typeof value === "number" && Number.isFinite(value));
      const lifeScoreDelta7d =
        lifeScoreWindow7d.length >= 2 ? round1(lifeScoreWindow7d[lifeScoreWindow7d.length - 1] - lifeScoreWindow7d[0]) : null;
      const highRiskStreak = countTrailingTrue(
        dayKeys
          .slice(0, index + 1)
          .map((key) => (metricsByDay.get(key)?.risk ?? 0) >= 68)
      );
      const highBurnoutStreak = countTrailingTrue(
        dayKeys
          .slice(0, index + 1)
          .map((key) => (metricsByDay.get(key)?.burnout ?? 0) >= 66)
      );
      const overloadStreak = countTrailingTrue(
        dayKeys
          .slice(0, index + 1)
          .map((key) => (bioByDay.get(key)?.overloadLevel ?? 0) >= 1)
      );
      const failedRecoveryStreak = countTrailingTrue(
        dayKeys.slice(0, index + 1).map((key) => {
          const bio = bioByDay.get(key);
          const dayMetrics = metricsByDay.get(key);
          if (!bio || !dayMetrics) return false;
          return (
            bio.recoveryDebt >= 62 &&
            bio.adaptiveCapacity <= 45 &&
            dayMetrics.load - dayMetrics.recovery >= 6
          );
        })
      );
      const loadRecoveryGap = metrics ? round1(metrics.load - metrics.recovery) : null;

      const totalDone = totalByDay.get(dayKey) ?? 0;
      const checkinsNeeded = Math.max(1, targetUserState.calibrationCheckinsNeeded ?? 7);
      const calibrationConfidence = clamp(totalDone / checkinsNeeded, 0, 1);
      const calibrationStage = getCalibrationStage(totalDone, calibrationConfidence);
      const onboardingProgressCheckins = Math.max(0, Math.min(7, totalDone));

      const activeProtocol = appliedRuns.find((run) => {
        if (!run.appliedAt) return false;
        const appliedAt = run.appliedAt.getTime();
        const expiresAt = appliedAt + run.horizonHours * 60 * 60 * 1000;
        return appliedAt <= dayEnd.getTime() && dayEnd.getTime() < expiresAt;
      });

      const activeProtocolConstraints = parseProtocolConstraints(activeProtocol?.protocol);
      const protocolInputs =
        activeProtocol?.inputs && typeof activeProtocol.inputs === "object"
          ? (activeProtocol.inputs as Record<string, unknown>)
          : null;
      const activeProtocolTriggerContext = parseProtocolTriggerContext(activeProtocol?.inputs);
      const protocolRiskAtApply =
        protocolInputs && typeof protocolInputs.risk === "number" && Number.isFinite(protocolInputs.risk)
          ? protocolInputs.risk
          : null;
      const protocolMinRecovery =
        protocolInputs && typeof protocolInputs.recovery === "number" && Number.isFinite(protocolInputs.recovery)
          ? protocolInputs.recovery
          : null;

      const computedIntegrity = metrics
        ? computeIntegrity({
            activeProtocol: activeProtocol
              ? {
                  constraints: activeProtocolConstraints,
                  riskAtApply: protocolRiskAtApply,
                  requiredMinRecovery: protocolMinRecovery,
                }
              : null,
            currentInputs: {
              deepWorkMinutes: checkinParsed.deepWorkMin ?? 0,
              stress: checkinRow?.stressLevel ?? checkinParsed.stress ?? null,
              workoutIntensity: typeof checkinParsed.workout === "number" ? checkinParsed.workout : null,
            },
            currentRisk: metrics.risk,
            currentRecovery: metrics.recovery,
          })
        : { score: 100, state: "STABLE" as const, violations: [] };

      const guardrailResult = metrics
        ? evaluateGuardrailWithContext({
            currentRisk: metrics.risk,
            avgRisk14d: avgRisk14d ?? metrics.risk,
            burnout: metrics.burnout,
            confidence: calibrationConfidence,
            adaptiveRiskOffset: targetUserState.adaptiveRiskOffset ?? 0,
            recoveryDebt: bioRow?.recoveryDebt ?? null,
            adaptiveCapacity: bioRow?.adaptiveCapacity ?? null,
            resilience: bioRow?.resilienceIndex ?? null,
            overloadLevel: bioRow?.overloadLevel ?? null,
            lifeScore: asNumber(statRow?.lifeScore),
            lifeScoreDelta7d,
            riskDelta7d,
            burnoutDelta7d,
            load: metrics.load,
            recovery: metrics.recovery,
            recoveryPattern: deriveRecoveryPatternForGuardrail({
              lifeScoreDelta7d,
              riskDelta7d,
              burnoutDelta7d,
              load: metrics.load,
              recovery: metrics.recovery,
              sleepHours: checkinParsed.sleepHours ?? null,
              sleepQuality: checkinParsed.sleepQuality ?? null,
              stress: checkinRow?.stressLevel ?? checkinParsed.stress ?? null,
              deepWorkMin: checkinParsed.deepWorkMin ?? null,
              workout: checkinParsed.workout ?? null,
              circadianAlignment: bioRow?.circadianAlignment ?? 0,
            }),
          })
        : null;
      const guardrail = guardrailResult
        ? {
            level: guardrailResult.level,
            label: guardrailResult.label,
            reasons: guardrailResult.reasons,
          }
        : { level: 0 as const, label: "OPEN" as const, reasons: [] as string[] };
      const guardrailDebug = guardrailResult?.context ?? null;

      const authority = deriveSystemStatus({
        guardrailState: guardrail.label,
        integrityState: computedIntegrity.state,
        hasActiveProtocol: Boolean(activeProtocol),
        risk24h: metrics?.risk ?? null,
        modelConfidence: calibrationConfidence,
        calibrationStage: calibrationStage.stage,
      });

      const topContributions = [...dayContributions]
        .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution))
        .slice(0, 5)
        .map((line) => ({
          statType: line.statType,
          factorType: line.factorType,
          factorLabel: factorLabel(line.factorType),
          contribution: round1(line.contribution),
        }));
      const primaryDriver = topContributions[0]?.factorLabel ?? "No dominant driver";

      const trajectorySeries7d = dayKeys
        .slice(Math.max(0, index - 6), index + 1)
        .map((key) => {
          const row = statsByDay.get(key);
          if (!row) return null;
          return {
            date: key,
            lifeScore: asNumber(row.lifeScore),
          };
        })
        .filter((row): row is { date: string; lifeScore: number | null } => row !== null);

      return {
        dayIndex: index + 1,
        date: dayKey,
        checkinInput: checkinRow
          ? {
              id: checkinRow.id,
              createdAt: checkinRow.createdAt.toISOString(),
              updatedAt: checkinRow.updatedAt.toISOString(),
              mood: checkinRow.mood,
              stressLevel: checkinRow.stressLevel,
              energyLevel: checkinRow.energyLevel,
              systemStatus: checkinRow.systemStatus,
              configVersion: checkinRow.configVersion,
              bedtimeMinutes: checkinRow.bedtimeMinutes ?? checkinParsed.bedtimeMinutes ?? null,
              wakeTimeMinutes: checkinRow.wakeTimeMinutes ?? checkinParsed.wakeTimeMinutes ?? null,
              sleepHours: checkinParsed.sleepHours ?? null,
              sleepQuality: checkinParsed.sleepQuality ?? null,
              workout: checkinParsed.workout ?? null,
              deepWorkMin: checkinParsed.deepWorkMin ?? null,
              learningMin: checkinParsed.learningMin ?? null,
              moneyDelta: checkinParsed.moneyDelta ?? null,
              noteText: checkinParsed.noteText ?? null,
            }
          : null,
        computedState: {
          lifeScore: asNumber(statRow?.lifeScore),
          guardrailState: guardrail.label,
          guardrailReasons: guardrail.reasons,
          confidence: {
            value: round1(calibrationConfidence),
            pct: Math.round(calibrationConfidence * 100),
            source: "calibration-progress",
          },
          authority: {
            status: authority.status,
            rationale: authority.rationale,
          },
          calibration: {
            stage: calibrationStage.stage,
            progressText: calibrationStage.progressText,
            noteText: calibrationStage.noteText,
            checkinsDone: totalDone,
            checkinsNeeded,
            onboardingProgressCheckins,
          },
          snapshot: statRow
            ? {
                id: statRow.id,
                configVersion: statRow.configVersion,
                rawStatus: statRow.systemStatus,
                stats: {
                  energy: asNumber(statRow.health),
                  focus: asNumber(statRow.relationships),
                  discipline: asNumber(statRow.career),
                  finance: asNumber(statRow.finance),
                  growth: asNumber(statRow.personalGrowth),
                },
              }
            : null,
        },
        diagnostics: {
          systemMetrics: metrics
            ? {
                recoveryCapacity: metrics.recovery,
                loadPressure: metrics.load,
                riskProbability: metrics.risk,
                burnoutRisk: metrics.burnout,
                avgRisk14d,
              }
            : null,
          systemDrift: {
            state: computedIntegrity.state,
            score: round1(computedIntegrity.score),
            violations: computedIntegrity.violations,
          },
          antiChaos: antiChaosStatePlan
            ? {
                id: antiChaosStatePlan.id,
                state: antiChaosState,
                active: antiChaosState === "warning" || antiChaosState === "critical",
                systemStatus: antiChaosStatePlan.systemStatus,
                isResolved: antiChaosState === "resolved_history",
                resolvedDate: antiChaosStatePlan.resolvedDate ? antiChaosStatePlan.resolvedDate.toISOString() : null,
                reasons: antiChaosStatePlan.reasons,
                actionItems: antiChaosStatePlan.actionItems,
              }
            : null,
          antiChaosState: {
            state: antiChaosState,
            activePlanId: antiChaosActive?.id ?? null,
            historyPlanId: antiChaosStatePlan?.id ?? null,
          },
          protocol: {
            state: activeProtocol
              ? "active"
              : generatedProtocols.length > 0
                ? "generated"
                : clearedProtocols.length > 0
                  ? "cleared"
                  : "inactive",
            active: activeProtocol
              ? {
                  id: activeProtocol.id,
                  mode: activeProtocol.mode,
                  guardrailState: activeProtocol.guardrailState,
                  confidence: activeProtocol.confidence,
                  horizonHours: activeProtocol.horizonHours,
                  appliedAt: activeProtocol.appliedAt ? activeProtocol.appliedAt.toISOString() : null,
                  constraintsCount: countConstraints(activeProtocol.protocol),
                  triggerContext: activeProtocolTriggerContext,
                }
              : null,
            generatedToday: generatedProtocols.map((run) => {
              const triggerContext = parseProtocolTriggerContext(run.inputs);
              return {
                id: run.id,
                mode: run.mode,
                guardrailState: run.guardrailState,
                confidence: run.confidence,
                horizonHours: run.horizonHours,
                createdAt: run.createdAt.toISOString(),
                appliedAt: run.appliedAt ? run.appliedAt.toISOString() : null,
                constraintsCount: countConstraints(run.protocol),
                triggerContext,
              };
            }),
            clearedToday: clearedProtocols.map((run) => {
              const triggerContext = parseProtocolTriggerContext(run.inputs);
              return {
                id: run.id,
                mode: run.mode,
                guardrailState: run.guardrailState,
                createdAt: run.createdAt.toISOString(),
                clearReason: getAutoClearReason(run.outcome),
                triggerContext,
              };
            }),
          },
          trajectory: {
            series7d: trajectorySeries7d,
            lifeScoreDelta7d,
            pointsCount7d: trajectorySeries7d.length,
          },
          bioState: bioRow
            ? {
                energyReserve: round1(bioRow.energyReserve),
                cognitiveFatigue: round1(bioRow.cognitiveFatigue),
                strainIndex: round1(bioRow.strainIndex),
                overloadLevel: bioRow.overloadLevel,
                recoveryDebt: round1(bioRow.recoveryDebt),
                adaptiveCapacity: round1(bioRow.adaptiveCapacity),
                sleepBuffer: round1(bioRow.sleepBuffer),
                circadianAlignment: round1(bioRow.circadianAlignment),
                sleepRegularity: round1(bioRow.sleepRegularity),
                stressLoad: round1(bioRow.stressLoad),
                trainingBuffer: round1(bioRow.trainingBuffer),
                homeostasisBias: round1(bioRow.homeostasisBias),
                cognitiveSaturation: round1(bioRow.cognitiveSaturation),
                sympatheticDrive: round1(bioRow.sympatheticDrive),
                parasympatheticDrive: round1(bioRow.parasympatheticDrive),
                autonomicBalance: round1(bioRow.autonomicBalance),
                hormeticSignal: round1(bioRow.hormeticSignal),
                overstressSignal: round1(bioRow.overstressSignal),
                burnoutRiskIndex: round1(bioRow.burnoutRiskIndex),
                resilienceIndex: round1(bioRow.resilienceIndex),
              }
            : null,
          modelSignals: {
            primaryDriver,
            stabilityState: stabilityStateFromGuardrail(guardrail.label),
            topDiagnosticDrivers: topContributions,
          },
          controlLayerDebug: {
            guardrailControlScore: guardrailDebug?.controlPressureScore ?? null,
            guardrailControlScoreAfterRelief: guardrailDebug?.controlPressureAfterRelief ?? null,
            guardrailRecoveryReliefScore: guardrailDebug?.recoveryReliefScore ?? null,
            guardrailTriggerReasons: guardrail.reasons,
            guardrailPressureReasons: guardrailDebug?.pressureReasons ?? [],
            guardrailRecoveryReasons: guardrailDebug?.recoveryReasons ?? [],
            guardrailEmergencyReasons: guardrailDebug?.emergencyReasons ?? [],
            guardrailEmergencyTriggered: guardrailDebug?.emergencyTriggered ?? false,
            guardrailSevereSignalCount: guardrailDebug?.severeSignalCount ?? 0,
            protocolTriggerReason: {
              active: activeProtocolTriggerContext.triggerReasons,
              generatedToday: generatedProtocols.flatMap((run) => parseProtocolTriggerContext(run.inputs).triggerReasons),
              clearedToday: clearedProtocols.flatMap((run) => parseProtocolTriggerContext(run.inputs).triggerReasons),
            },
            protocolGuardrailPressureReasons: {
              active: activeProtocolTriggerContext.guardrailPressureReasons,
              generatedToday: generatedProtocols.flatMap((run) =>
                parseProtocolTriggerContext(run.inputs).guardrailPressureReasons
              ),
              clearedToday: clearedProtocols.flatMap((run) =>
                parseProtocolTriggerContext(run.inputs).guardrailPressureReasons
              ),
            },
            antiChaosTriggerReason:
              antiChaosState === "warning" || antiChaosState === "critical"
                ? antiChaosStatePlan?.reasons ?? []
                : [],
            recentTrendSummary: {
              windowDays: 7,
              avgRisk7d: recentRiskWindow.length > 0 ? round1(average(recentRiskWindow)) : null,
              avgRisk14d,
              riskDelta7d,
              burnoutDelta7d,
              lifeScoreDelta7d,
              loadRecoveryGap,
              highRiskStreakDays: highRiskStreak,
              highBurnoutStreakDays: highBurnoutStreak,
              overloadStreakDays: overloadStreak,
              failedRecoveryStreakDays: failedRecoveryStreak,
            },
          },
          contributions: {
            total: dayContributions.length,
            top: topContributions,
            all: dayContributions.map((line) => ({
              statType: line.statType,
              factorType: line.factorType,
              factorLabel: factorLabel(line.factorType),
              contribution: round1(line.contribution),
            })),
          },
        },
        events: [] as Array<{
          type: string;
          label: string;
          from?: string | number | null;
          to?: string | number | null;
          details?: string;
        }>,
        _internal: {
          totalCheckinsToDate: totalDone,
          onboardingProgressCheckins,
          activeProtocolId: activeProtocol?.id ?? null,
        },
      };
    });

    const milestoneThresholds: Array<1 | 3 | 5 | 7> = [1, 3, 5, 7];
    for (let index = 0; index < dayRecords.length; index += 1) {
      const current = dayRecords[index];
      const previous = index > 0 ? dayRecords[index - 1] : null;
      const currentTotal = current._internal.totalCheckinsToDate;
      const previousTotal = previous?._internal.totalCheckinsToDate ?? 0;

      if (!current.checkinInput) {
        current.events.push({
          type: "missing_checkin",
          label: "No check-in found for this operational day.",
        });
      }

      for (const threshold of milestoneThresholds) {
        if (previousTotal < threshold && currentTotal >= threshold) {
          current.events.push({
            type: "milestone_unlocked",
            label: `Milestone Day ${threshold} reached.`,
            from: previousTotal,
            to: currentTotal,
          });
          if (threshold === 3) {
            current.events.push({
              type: "trajectory_unlocked",
              label: "7-day trajectory unlock threshold reached.",
            });
          } else if (threshold === 5) {
            current.events.push({
              type: "diagnostics_partial_unlocked",
              label: "Partial diagnostics unlock threshold reached.",
            });
          } else if (threshold === 7) {
            current.events.push({
              type: "diagnostics_full_unlocked",
              label: "Full diagnostics unlock threshold reached.",
            });
          }
        }
      }

      if (previous) {
        if (previous.computedState.guardrailState !== current.computedState.guardrailState) {
          current.events.push({
            type: "guardrail_transition",
            label: "Guardrail state transitioned.",
            from: previous.computedState.guardrailState,
            to: current.computedState.guardrailState,
          });
        }
        if (previous.computedState.authority.status !== current.computedState.authority.status) {
          current.events.push({
            type: "authority_transition",
            label: "Authority status transitioned.",
            from: previous.computedState.authority.status,
            to: current.computedState.authority.status,
          });
        }
        if (previous.computedState.calibration.stage !== current.computedState.calibration.stage) {
          current.events.push({
            type: "calibration_transition",
            label: "Calibration stage transitioned.",
            from: previous.computedState.calibration.stage,
            to: current.computedState.calibration.stage,
          });
        }
        if (previous._internal.activeProtocolId !== current._internal.activeProtocolId) {
          current.events.push({
            type: "protocol_transition",
            label: "Active protocol state changed.",
            from: previous._internal.activeProtocolId,
            to: current._internal.activeProtocolId,
          });
        }

        const previousDriftState = previous.diagnostics.systemDrift.state;
        const currentDriftState = current.diagnostics.systemDrift.state;
        if (previousDriftState !== currentDriftState) {
          current.events.push({
            type: "drift_transition",
            label: "System drift state transitioned.",
            from: previousDriftState,
            to: currentDriftState,
          });
        }
      }

      const antiChaosNowState = current.diagnostics.antiChaosState.state;
      const antiChaosPrevState = previous?.diagnostics.antiChaosState.state ?? "inactive";
      const antiChaosNow = current.diagnostics.antiChaos;
      const antiChaosNowActive = antiChaosNowState === "warning" || antiChaosNowState === "critical";
      const antiChaosPrevActive = antiChaosPrevState === "warning" || antiChaosPrevState === "critical";
      if (antiChaosNowActive && !antiChaosPrevActive && antiChaosNow?.id) {
        current.events.push({
          type: "anti_chaos_generated",
          label: "Anti-Chaos plan present for this day.",
          to: antiChaosNow.id,
        });
      }
      if (antiChaosPrevActive && (antiChaosNowState === "resolved_history" || antiChaosNowState === "inactive")) {
        current.events.push({
          type: "anti_chaos_resolved",
          label: "Anti-Chaos plan marked as resolved.",
          to: antiChaosNow?.id ?? null,
        });
      }
    }

    const generatedCheckins = checkins.map((row) => {
      const parsed = parseCheckinPayload(row.notes);
      return {
        id: row.id,
        date: formatDateOnly(row.date),
        createdAt: row.createdAt.toISOString(),
        updatedAt: row.updatedAt.toISOString(),
        stressLevel: row.stressLevel,
        mood: row.mood,
        energyLevel: row.energyLevel,
        systemStatus: row.systemStatus,
        bedtimeMinutes: row.bedtimeMinutes ?? parsed.bedtimeMinutes ?? null,
        wakeTimeMinutes: row.wakeTimeMinutes ?? parsed.wakeTimeMinutes ?? null,
        sleepHours: parsed.sleepHours ?? null,
        sleepQuality: parsed.sleepQuality ?? null,
        workout: parsed.workout ?? null,
        deepWorkMin: parsed.deepWorkMin ?? null,
        learningMin: parsed.learningMin ?? null,
        moneyDelta: parsed.moneyDelta ?? null,
        stress: parsed.stress ?? row.stressLevel ?? null,
        noteText: parsed.noteText ?? null,
      };
    });

    const simulatedDetected = generatedCheckins.filter((row) =>
      SIMULATION_NOTE_MARKERS.some((marker) => row.noteText?.includes(marker))
    ).length;
    const generatedAt = new Date();
    const filename = `life-os-simulation-log-${toTimestampFilePart(generatedAt)}.json`;

    return NextResponse.json(
      {
        ok: true,
        data: {
          meta: {
            userId: user.id,
            generatedAt: generatedAt.toISOString(),
            mode: payload.mode,
            version: process.env.NEXT_PUBLIC_APP_VERSION ?? "dev",
            filename,
            startDate: payload.startDateISO,
            endDate: payload.endDateISO,
            days: rangeDays,
            requestedDays: payload.days,
            generatedCheckinsCount: generatedCheckins.length,
            simulationMarkerDetectedCount: simulatedDetected,
          },
          generatedCheckins,
          days: dayRecords.map(({ _internal, ...publicDay }) => publicDay),
        },
      },
      {
        status: 200,
        headers: { "Cache-Control": "no-store" },
      }
    );
  } catch (error) {
    return errorResponse(error);
  }
}
