import { LifeOSBackground } from "@/components/layout/LifeOSBackground";
import { PublicFooter } from "@/components/public/PublicFooter";
import { PageHeader } from "@/components/public/PageHeader";

export default function PrivacyPage() {
  return (
    <LifeOSBackground>
      <main className="mx-auto min-h-screen w-full max-w-4xl px-6 py-10 text-zinc-100 sm:py-12">
        <PageHeader
          kicker="LEGAL"
          title="Privacy"
          showBackToHome
        />

        <section className="space-y-4 rounded-xl border border-zinc-800 bg-zinc-900/70 p-5 text-sm text-zinc-300">
          <div>
            <h2 className="text-base font-semibold text-zinc-100">What data is stored</h2>
            <p className="mt-1">
              Daily check-ins, protocol runs, scenario runs, and operational event records generated by system actions.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-zinc-100">What data is not stored</h2>
            <p className="mt-1">
              No medical diagnosis data, no black-box AI inference outputs, and no sale of personal data.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-zinc-100">Data retention</h2>
            <p className="mt-1">Data is retained until account deletion or until manually reset where supported.</p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-zinc-100">User controls</h2>
            <ul className="mt-1 space-y-1">
              <li>- Export System Log</li>
              <li>- Reset System</li>
              <li>- Delete Account</li>
            </ul>
          </div>

          <div>
            <h2 className="text-base font-semibold text-zinc-100">Contact</h2>
            <p className="mt-1">Contact: email on request.</p>
          </div>
        </section>
        <PublicFooter className="mt-8" />
      </main>
    </LifeOSBackground>
  );
}
