import { LifeOSBackground } from "@/components/layout/LifeOSBackground";
import { BackNavButton } from "@/components/ui/BackNavButton";
import { PublicFooter } from "@/components/public/PublicFooter";
import { getSupportEmail } from "@/lib/supportContact";

export default function PrivacyPage() {
  const supportEmail = getSupportEmail();
  const mailtoHref = `mailto:${supportEmail}?subject=${encodeURIComponent("LIFE OS Privacy Request")}`;

  return (
    <LifeOSBackground>
      <main className="mx-auto min-h-screen w-full max-w-5xl overflow-x-hidden px-4 py-10 text-zinc-100 sm:px-6 sm:py-12">
        <header className="mb-8 sm:mb-10">
          <BackNavButton fallbackHref="/" label="← Back to Home" variant="text" navigation="href" />
          <div className="mt-4 space-y-2">
            <p className="text-xs uppercase tracking-[0.24em] text-zinc-500">LEGAL</p>
            <h1 className="text-3xl font-semibold text-zinc-100 sm:text-4xl">Privacy</h1>
            <p className="max-w-3xl text-sm leading-relaxed text-zinc-400">
              Product-specific privacy summary for data used by LIFE OS operation.
            </p>
          </div>
        </header>

        <section className="space-y-6 rounded-xl border border-zinc-800 bg-zinc-900/70 p-5 text-sm leading-relaxed text-zinc-300">
          <div>
            <h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">What data is stored</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>Daily check-ins and associated signal fields.</li>
              <li>Deterministic operational outputs (for example: snapshots, diagnostics state, trajectory context, protocol runs).</li>
              <li>Scenario artifacts when scenario/planning tools are used.</li>
              <li>Account/session and billing records required for access and subscription lifecycle.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">What data is not stored</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>No medical diagnosis records generated by LIFE OS.</li>
              <li>No opaque black-box recommendation logs as a primary control layer.</li>
              <li>No sale of personal data.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">Data retention</h2>
            <p className="mt-3">
              Operational data is retained for account continuity until user-initiated reset or account deletion.
            </p>
          </div>

          <div>
            <h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">User controls</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>`Export System Log`: exports stored check-in and protocol history for selected range.</li>
              <li>`Reset System`: clears operational history and restarts calibration state.</li>
              <li>`Delete Account`: removes account and linked operational/billing records.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">Contact</h2>
            <a href={mailtoHref} className="mt-3 inline-flex min-h-10 break-all rounded-md border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-sm text-zinc-200 transition hover:border-zinc-500">
              {supportEmail}
            </a>
          </div>
        </section>
        <PublicFooter className="mt-10" />
      </main>
    </LifeOSBackground>
  );
}
