-- v3.8 Autonomic Balance model
ALTER TABLE "BioStateSnapshot"
ADD COLUMN "sympatheticDrive" DOUBLE PRECISION NOT NULL DEFAULT 40,
ADD COLUMN "parasympatheticDrive" DOUBLE PRECISION NOT NULL DEFAULT 40,
ADD COLUMN "autonomicBalance" DOUBLE PRECISION NOT NULL DEFAULT 50;

ALTER TABLE "WeightConfig"
ADD COLUMN "sympCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.78,
ADD COLUMN "paraCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.78,
ADD COLUMN "sympFromStress" DOUBLE PRECISION NOT NULL DEFAULT 0.55,
ADD COLUMN "sympFromLoad" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
ADD COLUMN "sympFromStrain" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN "paraFromSleep" DOUBLE PRECISION NOT NULL DEFAULT 0.45,
ADD COLUMN "paraFromRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
ADD COLUMN "paraFromCircadian" DOUBLE PRECISION NOT NULL DEFAULT 0.25,
ADD COLUMN "paraSuppressedByStressLoad" DOUBLE PRECISION NOT NULL DEFAULT 0.25;
