-- Bio v3.3: delayed recovery via sleep buffer

ALTER TABLE "WeightConfig"
  ADD COLUMN IF NOT EXISTS "bufferGain" DOUBLE PRECISION NOT NULL DEFAULT 0.6,
  ADD COLUMN IF NOT EXISTS "bufferCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.65,
  ADD COLUMN IF NOT EXISTS "bufferSpendMax" DOUBLE PRECISION NOT NULL DEFAULT 35,
  ADD COLUMN IF NOT EXISTS "reserveFromBuffer" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
  ADD COLUMN IF NOT EXISTS "fatigueFromBuffer" DOUBLE PRECISION NOT NULL DEFAULT 0.45;

ALTER TABLE "BioStateSnapshot"
  ADD COLUMN IF NOT EXISTS "sleepBuffer" DOUBLE PRECISION NOT NULL DEFAULT 0;
