-- Bio v3.5 / v3.6: stress carry-over + training adaptation lag

ALTER TABLE "WeightConfig"
  ADD COLUMN IF NOT EXISTS "stressCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
  ADD COLUMN IF NOT EXISTS "stressGain" DOUBLE PRECISION NOT NULL DEFAULT 0.9,
  ADD COLUMN IF NOT EXISTS "stressRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
  ADD COLUMN IF NOT EXISTS "trainingIn" DOUBLE PRECISION NOT NULL DEFAULT 35,
  ADD COLUMN IF NOT EXISTS "trainingCarry" DOUBLE PRECISION NOT NULL DEFAULT 0.70,
  ADD COLUMN IF NOT EXISTS "trainingSpendMax" DOUBLE PRECISION NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "trainingReserveBonus" DOUBLE PRECISION NOT NULL DEFAULT 0.18,
  ADD COLUMN IF NOT EXISTS "trainingDisciplineBonus" DOUBLE PRECISION NOT NULL DEFAULT 0.28,
  ADD COLUMN IF NOT EXISTS "trainingAdaptiveBonus" DOUBLE PRECISION NOT NULL DEFAULT 0.12,
  ADD COLUMN IF NOT EXISTS "workoutSameDayCostReserve" DOUBLE PRECISION NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS "workoutSameDayCostFatigue" DOUBLE PRECISION NOT NULL DEFAULT 6;

ALTER TABLE "BioStateSnapshot"
  ADD COLUMN IF NOT EXISTS "stressLoad" DOUBLE PRECISION NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "trainingBuffer" DOUBLE PRECISION NOT NULL DEFAULT 0;
